[config]
skip_core_tasks = true

[tasks.format]
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.changelog]
workspace = false
install_crate = "git-cliff"
command = "git-cliff"
args = ["-o=CHANGELOG.md"]

[tasks.watch]
workspace = false
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "test --all -- --nocapture"]

[tasks.doc-build]
install_crate = "mdbook"
cwd = "docs"
workspace = false
command = "mdbook"
args = ["build"]

[tasks.doc-serve]
install_crate = "mdbook"
cwd = "docs"
workspace = false
command = "mdbook"
args = ["serve"]