[book]
title = "Brainease"
authors = ["arthurfiorette"]
description = "A brainf*ck-style programming language, but readable"
src = "src"
language = "en"
multilingual = false

[output.html]
site-url = "/brainease/"
git-repository-url = "https://github.com/arthurfiorette/brainease"
edit-url-template = "https://github.com/arthurfiorette/brainease/edit/main/docs/{path}"
additional-js = ["./assets/bf-memory.js"]
additional-css = ["./assets/styles.css"]

[rust]
edition = "2021"
