name: Deploy docs

on:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Cache cargo files
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install required packages
        run: cargo install mdbook cargo-make --force

      - name: Build docs
        run: cargo make docs-build

      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: ./docs/book/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
