name: Publish to crates.io

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    name: Test, Lint and Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all -- -D warnings

      - name: Run test
        run: cargo test --all

      - name: Run check
        run: cargo check --all

  publish:
    needs: [test]
    name: Publish monorepo
    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Login to crates.io
        run: cargo login

      - name: Publish lexer to crates.io
        run: cargo publish --package brainease_lexer

      - run: sleep 15

      - name: Publish transpiler to crates.io
        run: cargo publish --package brainease_transpiler

      - run: sleep 15

      - name: Publish runtime to crates.io
        run: cargo publish --package brainease_runtime

      - run: sleep 15

      - name: Publish cli to crates.io
        run: cargo publish --package brainease

  attach:
    needs: [test]
    name: Attach binaries on latest release (${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary_target: x86_64-unknown-linux-musl
            toolchain: stable

          - os: windows-latest
            binary_target: x86_64-pc-windows-msvc
            toolchain: stable-x86_64-pc-windows-msvc

          - os: macos-latest
            binary_target: x86_64-apple-darwin
            toolchain: stable
          
          - os: arm-latest
            binary_target: armv7-unknown-linux-musleabihf
            toolchain: stable-armv7-unknown-linux-musleabihf

    steps:
      - name: Install musl tools
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install musl-tools

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - name: Build binaries
        run: cargo build --all --release

      - name: Zip binaries
        uses: vimtor/action-zip@v1
        with:
          files:
            README.md LICENSE target/release/${{ (matrix.os == 'windows-latest' &&
            'brainz.exe') || 'brainz'}}
          dest: brainease-${{ matrix.binary_target }}.zip

      - name: Upload Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: brainease-${{ matrix.binary_target }}.zip
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
