name: Publish to crates.io

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    name: Test, Lint and Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Cache cargo files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Run test
        run: cargo test

      - name: Run check
        run: cargo check

  publish:
    needs: [test]
    name: Publish monorepo
    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Login to crates.io
        run: cargo login

      - name: Publish lexer to crates.io
        run: cargo publish --package brainease_lexer

      - name: Publish runtime to crates.io
        run: cargo publish --package brainease_runtime

      - name: Publish cli to crates.io
        run: cargo publish
